import { PMTiles } from "pmtiles";
import Pbf from "pbf";
import { VectorTile } from "@mapbox/vector-tile";
import { latLngToTile } from "../tiles";
import type { Feature, Polygon, MultiPolygon } from "geojson";
import { openDB, type IDBPDatabase, type DBSchema } from "idb";

// IndexedDB schema for caching reverse geocoding results
interface LookupCacheDB extends DBSchema {
	lookupResults: {
		key: string; // coordinate bucket key "lat,lng" rounded to 1 decimal
		value: {
			key: string;
			result: WorldLookupResult | null;
			timestamp: number;
		};
	};
}

let lookupDb: IDBPDatabase<LookupCacheDB> | null = null;
const LOOKUP_CACHE_MAX_AGE_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

async function getLookupDb(): Promise<IDBPDatabase<LookupCacheDB>> {
	if (lookupDb) return lookupDb;
	lookupDb = await openDB<LookupCacheDB>("world-lookup-cache", 1, {
		upgrade(db) {
			if (!db.objectStoreNames.contains("lookupResults")) {
				db.createObjectStore("lookupResults", { keyPath: "key" });
			}
		},
	});
	return lookupDb;
}

function coordBucketKey(lat: number, lng: number): string {
	// Round to 3 decimals (~100-200m) for finer granularity with smaller cities
	return `${lat.toFixed(3)},${lng.toFixed(3)}`;
}

async function getCachedLookup(
	lat: number,
	lng: number,
): Promise<WorldLookupResult | null | undefined> {
	try {
		const db = await getLookupDb();
		const key = coordBucketKey(lat, lng);
		const record = await db.get("lookupResults", key);
		if (record && Date.now() - record.timestamp < LOOKUP_CACHE_MAX_AGE_MS) {
			// Return the cached result (could be null if no city was found)
			return record.result;
		}
	} catch (e) {
		console.warn("Failed to read lookup from cache:", e);
	}
	// undefined means cache miss, null means cached "no result"
	return undefined;
}

async function cacheLookupResult(
	lat: number,
	lng: number,
	result: WorldLookupResult | null,
): Promise<void> {
	try {
		const db = await getLookupDb();
		const key = coordBucketKey(lat, lng);
		await db.put("lookupResults", {
			key,
			result,
			timestamp: Date.now(),
		});
	} catch (e) {
		console.warn("Failed to cache lookup result:", e);
	}
}

/**
 * Result from a world lookup query — identifies a city at a given coordinate.
 */
export interface WorldLookupResult {
	/** OSM identifier used as filename key, e.g. "relation_12345" */
	osmId: string;
	/** City/municipality name from OSM name tag */
	name: string;
	/** Road PMTiles filename that covers this city, e.g. "europe.pmtiles" */
	roadTiles: string;
}

/** Ray-casting point-in-ring test. Coordinates are [lng, lat] pairs. */
function pointInRing(ring: number[][], px: number, py: number): boolean {
	const n = ring.length;
	let inside = false;
	let j = n - 1;
	for (let i = 0; i < n; i++) {
		const xi = ring[i][0],
			yi = ring[i][1];
		const xj = ring[j][0],
			yj = ring[j][1];
		if (yi > py !== yj > py && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) {
			inside = !inside;
		}
		j = i;
	}
	return inside;
}

/** Point-in-polygon check for a GeoJSON Polygon or MultiPolygon feature. */
function pointInGeoJSON(
	feature: Feature<Polygon | MultiPolygon>,
	lng: number,
	lat: number,
): boolean {
	if (feature.geometry.type === "Polygon") {
		const rings = feature.geometry.coordinates;
		if (!pointInRing(rings[0], lng, lat)) return false;
		for (let h = 1; h < rings.length; h++) {
			if (pointInRing(rings[h], lng, lat)) return false;
		}
		return true;
	} else {
		for (const poly of feature.geometry.coordinates) {
			if (!pointInRing(poly[0], lng, lat)) continue;
			let inHole = false;
			for (let h = 1; h < poly.length; h++) {
				if (pointInRing(poly[h], lng, lat)) {
					inHole = true;
					break;
				}
			}
			if (!inHole) return true;
		}
		return false;
	}
}

/**
 * The zoom level at which we query the world-lookup PMTiles.
 * z10 balances detail (polygon accuracy) with tile count.
 * z12 would be more precise but means more, larger tiles.
 * Tippecanoe generates tiles from z0–z12, so z10 is always available.
 */
const LOOKUP_ZOOM = 10;

/**
 * WorldLookup provides self-hosted reverse geocoding by querying a PMTiles
 * archive of admin_level=8 (city/municipality) boundaries.
 *
 * Usage:
 *   const lookup = new WorldLookup("https://your-cdn.com/lookup/world-lookup.pmtiles");
 *   const result = await lookup.query(48.1351, 11.582);
 *   // result = { osmId: "relation_62428", name: "München", roadTiles: "europe.pmtiles" }
 *
 * The PMTiles archive is generated by the boundary pipeline (run_boundaries.sh)
 * which enriches each feature with `osm_id` and `road_tiles` properties.
 */
export class WorldLookup {
	private pmtiles: PMTiles;
	private tileCache = new Map<string, VectorTile | null>();
	private static readonly MAX_CACHE_SIZE = 64;

	constructor(url: string);
	constructor(pmtiles: PMTiles);
	constructor(urlOrInstance: string | PMTiles) {
		if (typeof urlOrInstance === "string") {
			this.pmtiles = new PMTiles(urlOrInstance);
		} else {
			this.pmtiles = urlOrInstance;
		}
	}

	/**
	 * Query the lookup tiles for a city at the given coordinates.
	 * Returns the first matching city polygon that contains the point,
	 * or null if no city boundary covers this location.
	 *
	 * Results are cached in IndexedDB by coordinate bucket (~100m) to avoid
	 * redundant network requests on page reload.
	 */
	async query(lat: number, lng: number): Promise<WorldLookupResult | null> {
		// Check IndexedDB cache first
		const cached = await getCachedLookup(lat, lng);
		if (cached !== undefined) {
			// Cache hit (could be null if we previously found no city)
			return cached;
		}

		const result = await this.queryInternal(lat, lng);

		// Cache the result (including null for "no city found")
		await cacheLookupResult(lat, lng, result);

		return result;
	}

	/**
	 * Internal query implementation - performs the actual PMTiles lookup.
	 */
	private async queryInternal(lat: number, lng: number): Promise<WorldLookupResult | null> {
		const tile = await this.fetchTile(lat, lng, LOOKUP_ZOOM);
		if (!tile) return null;

		const { x, y } = latLngToTile(lat, lng, LOOKUP_ZOOM);

		// Find the "cities" layer in the vector tile
		const layer = tile.layers["cities"];
		if (!layer) return null;

		for (let i = 0; i < layer.length; i++) {
			const feature = layer.feature(i);
			const geojson = feature.toGeoJSON(x, y, LOOKUP_ZOOM);

			// Only check polygon/multipolygon geometries
			if (geojson.geometry.type !== "Polygon" && geojson.geometry.type !== "MultiPolygon") {
				continue;
			}

			if (pointInGeoJSON(geojson as Feature<Polygon | MultiPolygon>, lng, lat)) {
				const props = geojson.properties || {};
				const osmId = props.osm_id;
				const name = props.name || props["name:en"] || "";
				const roadTiles = props.road_tiles || "";

				if (!osmId) {
					console.warn("WorldLookup: matched feature has no osm_id property", props);
					continue;
				}

				return { osmId, name, roadTiles };
			}
		}

		// No polygon contained the point at this zoom — try one level higher for
		// better boundary precision (z12 is the max in our tileset)
		if (LOOKUP_ZOOM < 12) {
			const result = await this.queryAtZoom(lat, lng, 12);
			if (result) return result;
		}

		return null;
	}

	/**
	 * Query at a specific zoom level. Used as fallback for edge-case misses.
	 */
	private async queryAtZoom(
		lat: number,
		lng: number,
		zoom: number,
	): Promise<WorldLookupResult | null> {
		const tile = await this.fetchTile(lat, lng, zoom);
		if (!tile) return null;

		const { x, y } = latLngToTile(lat, lng, zoom);

		const layer = tile.layers["cities"];
		if (!layer) return null;

		for (let i = 0; i < layer.length; i++) {
			const feature = layer.feature(i);
			const geojson = feature.toGeoJSON(x, y, zoom);

			if (geojson.geometry.type !== "Polygon" && geojson.geometry.type !== "MultiPolygon") {
				continue;
			}

			if (pointInGeoJSON(geojson as Feature<Polygon | MultiPolygon>, lng, lat)) {
				const props = geojson.properties || {};
				const osmId = props.osm_id;
				const name = props.name || props["name:en"] || "";
				const roadTiles = props.road_tiles || "";

				if (!osmId) continue;
				return { osmId, name, roadTiles };
			}
		}

		return null;
	}

	/**
	 * Fetch and decode a vector tile, with caching.
	 */
	private async fetchTile(lat: number, lng: number, zoom: number): Promise<VectorTile | null> {
		const { x, y } = latLngToTile(lat, lng, zoom);
		const key = `${zoom}/${x}/${y}`;

		if (this.tileCache.has(key)) {
			return this.tileCache.get(key)!;
		}

		try {
			const resp = await this.pmtiles.getZxy(zoom, x, y);
			if (!resp || !resp.data) {
				this.tileCache.set(key, null);
				return null;
			}

			const vt = new VectorTile(new Pbf(new Uint8Array(resp.data as ArrayBuffer)));
			this.evictIfNeeded();
			this.tileCache.set(key, vt);
			return vt;
		} catch (e) {
			console.warn(`WorldLookup: failed to fetch tile ${key}:`, e);
			return null;
		}
	}

	/**
	 * Simple LRU-ish eviction: when the cache exceeds the max, drop the oldest half.
	 */
	private evictIfNeeded() {
		if (this.tileCache.size >= WorldLookup.MAX_CACHE_SIZE) {
			const keysToDelete = Array.from(this.tileCache.keys()).slice(
				0,
				Math.floor(WorldLookup.MAX_CACHE_SIZE / 2),
			);
			for (const key of keysToDelete) {
				this.tileCache.delete(key);
			}
		}
	}
}
